# Generated by Django 4.1.2 on 2022-10-15 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_cities_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='cities',
        ),
        migrations.AddField(
            model_name='cities',
            name='countries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.countries'),
        ),
    ]
