# Generated by Django 4.1.2 on 2022-10-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0008_rename_profile_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cities",
            name="countries",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="apis.countries",
            ),
        ),
    ]
